version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Yachatec-ApiRest
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300